### ISSUE TITLE
rec_polymerize.in

### ISSUE THREAD

**Issue by tmweigand** [tmweigand/membranes#11]
@ajotcham From your bridges account, I see you are running 'rec_polymerize.in' for polymerize. I do not see that file on the `bridges_prep`. Where did it come form? Did you just rename 'pack_polymerize_rec.in'? Did you test this out on a 1x domain on Bridges?

**Comment by tmweigand** [comment]
Can you change this line: [fix 1 all nvt temp 300 300 $(100.0*dt)](https://github.com/tmweigand/membranes/blob/3df2ad2bb109423efb0dff865f18e199cc693f5c/domain_generation/pack_polymerize_rec.in#L211) to ```fix 1 all nvt temp 300 300 $(1.*dt)```

Please submit that to Bridges and report back as soon as it finishes.

**Comment by ajotcham** [comment]
> @ajotcham From your bridges account, I see you are running 'rec_polymerize.in' for polymerize. I do not see that file on the `bridges_prep`. Where did it come form? Did you just rename 'pack_polymerize_rec.in'? Did you test this out on a 1x domain on Bridges?

Yes, I just renamed pack_polymerize_rec to make it easier to tab complete when I'm navigating through the terminal. It also has been tested on a 1x domain on bridges before.

**Comment by tmweigand** [comment]
ok cool. thats what I was figuring. Hope the reduction in timestep will solve that problem.

**Comment by ajotcham** [comment]
The sim ran and it still gets the same bond atoms missing error on bridges. This is for the 64x, 1.5 scale, 0.85 xlink case. 
[lammps_output.txt](https://github.com/user-attachments/files/17880112/lammps_output.txt)

**Comment by tmweigand** [comment]
Hi @ajotcham  I got an email from github where you wrote 
```The sim ran and it still gets the same bond atoms missing error on bridges. This is for the 64x, 1.5 scale, 0.85 xlink case.``` 
but I dont see the comment here. 

Anyway, I saw you made the change to the script and then I noticed I told you the incorrect line. My apologies. Please change this line instead and resubmit. 

https://github.com/tmweigand/membranes/blob/3df2ad2bb109423efb0dff865f18e199cc693f5c/domain_generation/pack_polymerize_rec.in#L139

Sorry about that.

**Comment by ajotcham** [comment]
Yea I deleted that cause I realized there were multiple lines of that in the code so I was gonna try to change the other lines but now I see. I changed the line you specified now and just submitted it so I'll report back when I get a result.

**Comment by ajotcham** [comment]
The 0.85 case had a new error I attached, and the 0.95 restart has the bond atoms missing error.
[0.85_lammps_error.txt](https://github.com/user-attachments/files/17937297/0.85_lammps_error.txt)
[0.85_lammps_output.txt](https://github.com/user-attachments/files/17937298/0.85_lammps_output.txt)
[0.95_lammps_error.txt](https://github.com/user-attachments/files/17937299/0.95_lammps_error.txt)
[0.95_lammps_output.txt](https://github.com/user-attachments/files/17937300/0.95_lammps_output.txt)

**Comment by tmweigand** [comment]
okay. thanks. Can submit these scripts for a cubic domain? So set the factor to 1.0. I am curious if these issues are related to lengthening of the domain. I will keep looking at this but that information will be helpful so let me know as soon as the run.

**Comment by ajotcham** [comment]
Hi sorry I couldn't reply yesterday I got my covid/flu vaccines yesterday afternoon and was a little sluggish. I got more errors when I changed the scale to 1.0.
[0.85_lammps_error.txt](https://github.com/user-attachments/files/17949013/0.85_lammps_error.txt)
[0.85_lammps_output.txt](https://github.com/user-attachments/files/17949014/0.85_lammps_output.txt)
[0.95_lammps_error.txt](https://github.com/user-attachments/files/17949015/0.95_lammps_error.txt)
[0.95_lammps_output.txt](https://github.com/user-attachments/files/17949016/0.95_lammps_output.txt)

**Comment by tmweigand** [comment]
Hi @ajotcham I just want to give you an update that I am still looking into this. I reverted back the changes in time step and  the code has run successfully multiple times with different random numbers and configurations. I am not sure why it is failing with the larger jobs.

**Comment by tmweigand** [comment]
@ajotcham On #8 I just pushed new files entitled `rec_polymerize_1_of_2.in` and `rec_polymerize_2_of_2.in.` Can you create new shell scripts for these and submit part 1 of 2 for both domains on Bridges? IF the complete, go ahead and submit part 2. Please report back if they fail.

**Comment by ajotcham** [comment]
Hi @tmweigand,
for the 0.85 case the 1 of 2 completed and then the 2 of 2 is still running currently.
For the 0.95 case the 1 of 2 said it completed, but the it was off about 4000 PA bonds from the target (wanted 54720 PA bonds, only formed 50748 bonds).

**Comment by tmweigand** [comment]
@ajotcham I think if you switch the 375 on this line:  [variable a loop 375](https://github.com/tmweigand/membranes/blob/2c765d54dc104eb55d38583e5330b14c14c07792/domain_generation/rec_polymerize_1_of_2.in#L107) to some large number, lets say 10000, we should be good.

**Comment by ajotcham** [comment]
ok I'll do that and submit it now

**Comment by ajotcham** [comment]
I just have a quick update on the jobs so far. The 0.85 xlink completed equilibration in about 10 hours so it is ready for hydration. And the 0.95 xlink is still running the 1 of 2 job right now.

**Comment by tmweigand** [comment]
Great! I will work on the hydration script this weekend and let you know when it is done.

**Comment by tmweigand** [comment]
@ajotcham I just pushed `hydration.in` and `hydration.sh` to `bridges_prep`. Please review the shell script before you submit to make sure everything is correct. I also added `hydration_restart.in` I would like you to go through and ensure it works. It should hopefully work as is. Thanks!

**Comment by ajotcham** [comment]
Hi @tmweigand I checked the hydration and it was giving me back some errors still for the 0.85 xlink job. I've attached the script I used to submit it as well as the error log and the output log.

[hydrate_shell.txt](https://github.com/user-attachments/files/18115668/hydrate_shell.txt)
[hydration_error.txt](https://github.com/user-attachments/files/18115665/hydration_error.txt)
[hydration_output.txt](https://github.com/user-attachments/files/18115666/hydration_output.txt)

**Comment by tmweigand** [comment]
Okay, I thought that my happen. Can you please change this line https://github.com/tmweigand/membranes/blob/dcf9a2f4fcbd56274e506b043843e283fd679524/domain_generation/hydrate.in#L43

to `lattice fcc 4.36` and resubmit. Thanks!

**Comment by tmweigand** [comment]
Any updates on the simulations?

**Comment by ajotcham** [comment]
I resubmitted the hydration for the 0.85 xlink case to see if the error I was getting is going to replicate. If it does, I'll send another update with the error message. For the 0.95 xlink case I was adapting my restart to reflect the new rec_polymerize files we have so that will be submitted later today.

**Comment by ajotcham** [comment]
Some job updates 
0.85 xlink
- I got the job for the hydration to extend to 1 week and now Im getting the restart going but I'm only submitting 48 hour jobs until I know those work for sure then I'll ask to extend hydration restarts for longer.

0.95 xlink
- I also extended this job to 1 week and its still in the PA bond formation stage and has a target of ~54500 bonds but only made 51600 in 1 week time. This 51600 number is only at 0.90 xlink currently since the total available bonds is 57600 I found. I'm getting a rec_polymerize_1_of_2 restart files going and hopefully it can keep making more bonds to get closer to the 0.95xlink target amount.

**Comment by tmweigand** [comment]
Thanks for the updates. that is annoying with the 95 xlink. Perhaps we should add more reactants to speed this up. I will reach out to Riley and see what he suggests.
